--CARGA INICIAL DE PRODUTOS
INSERT INTO  PRODUTO (DESCRICAO) VALUES ('AÇAI');

--CARGA INICIAL DE TAMANHOS
INSERT INTO  TAMANHO (DESCRICAO, QUANTIDADE, TEMPO, VALOR) VALUES ('PEQUENO',300, 5,10) ;
INSERT INTO  TAMANHO (DESCRICAO, QUANTIDADE, TEMPO, VALOR) VALUES ('MÉDIO',500, 7,13) ;
INSERT INTO  TAMANHO (DESCRICAO, QUANTIDADE, TEMPO, VALOR) VALUES ('GRANDE',700, 10,15) ;

--CARGA INICIAL DOS SABORES
INSERT INTO  SABOR(DESCRICAO, TEMPO) VALUES ('MORANGO',0) ;
INSERT INTO  SABOR(DESCRICAO, TEMPO) VALUES ('BANANA',0) ;
INSERT INTO  SABOR(DESCRICAO, TEMPO) VALUES ('KIWI',5) ;

--CARGA INICIAL DE ITEM_EXTRA
INSERT INTO  ITEM_EXTRA (DESCRICAO, TEMPO, VALOR) VALUES ('LEITE NINHO', 0,3) ;
INSERT INTO  ITEM_EXTRA (DESCRICAO, TEMPO, VALOR) VALUES ('GRANOLA',0,0) ;
INSERT INTO  ITEM_EXTRA (DESCRICAO, TEMPO, VALOR) VALUES ('PAÇOCA',3,3) ;

--CARGA INICIAL DE PEDIDO
INSERT INTO PEDIDO (SABOR_ID,TAMANHO_ID) VALUES (1,1);
INSERT INTO PEDIDO_ITEM_EXTRA (ITEM_ID,PEDIDO_ID) VALUES (1,1) ;
INSERT INTO PEDIDO_ITEM_EXTRA (ITEM_ID,PEDIDO_ID) VALUES (3,1) ;

